AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple Amazon Lex V2 bot with IAM role'

Resources:
  LexServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lexv2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LexV2BasicPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - polly:SynthesizeSpeech
                  - comprehend:DetectSentiment
                  - lambda:InvokeFunction
                Resource: '*'
      Description: 'IAM Role for Lex V2 Bot'
      RoleName: !Sub '${AWS::StackName}-lex-role'

  SimpleChatBot:
    Type: 'AWS::Lex::Bot'
    Properties:
      Name: SimpleChatBot
      Description: 'A simple chatbot created with CloudFormation'
      RoleArn: !GetAtt LexServiceRole.Arn
      DataPrivacy:
        ChildDirected: false
      IdleSessionTTLInSeconds: 300
      AutoBuildBotLocales: true
      BotLocales:
        - LocaleId: ja_JP
          NluConfidenceThreshold: 0.40
          VoiceSettings:
            VoiceId: Mizuki
          Intents:
            - Name: HelloIntent
              Description: 'Simple greeting intent'
              SampleUtterances:
                - Utterance: こんにちは
                - Utterance: はじめまして
                - Utterance: やあ
              FulfillmentCodeHook:
                Enabled: false
            - Name: FallbackIntent
              Description: 'Default intent when no other intent matches'
              ParentIntentSignature: AMAZON.FallbackIntent

  BotVersion:
    Type: 'AWS::Lex::BotVersion'
    DependsOn: SimpleChatBot
    Properties:
      BotId: !Ref SimpleChatBot
      BotVersionLocaleSpecification:
        - LocaleId: ja_JP
          BotVersionLocaleDetails:
            SourceBotVersion: DRAFT

  BotAlias:
    Type: 'AWS::Lex::BotAlias'
    DependsOn: BotVersion
    Properties:
      BotAliasName: prod
      BotId: !Ref SimpleChatBot
      BotAliasLocaleSettings:
        - LocaleId: ja_JP
          BotAliasLocaleSetting:
            Enabled: true
      BotVersion: "1"
      SentimentAnalysisSettings:
        DetectSentiment: false

Outputs:
  BotId:
    Description: 'The ID of the created bot'
    Value: !Ref SimpleChatBot
  BotAliasId:
    Description: 'The ID of the created bot alias'
    Value: !Ref BotAlias
  RoleArn:
    Description: 'The ARN of the IAM role'
    Value: !GetAtt LexServiceRole.Arn